version: '3.2'
services:

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80
    ports:
    - "8080:80"

  app:
    image: app
    container_name: app
    restart: unless-stopped
    volumes:
    - app:/app
    ports:
    - "8081:80"

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbit:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  postgres:
    image: postgres:13.3
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5555:80"

volumes:
  postgres:
  rabbit:
  pgadmin:
  app:


