version: '3.2'
services:

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
    - "8081:80"
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80

  app-1:
    image: app
    container_name: app-1
    restart: unless-stopped
    ports:
    - "8082:80"

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "15672:15672"
      - "5672:5672"

