version: '3.2'
services:

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
    - "8081:80"
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80

  app-1:
    image: app
    container_name: app-1
    restart: unless-stopped
    ports:
    - "8082:80"

  rabbit-1:
    image: rabbitmq:3-management
    hostname: rabbit-1
    container_name: rabbit-1
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "15672:15672"
      - "5672:5672"

  rabbit-2:
    image: rabbitmq:3-management
    hostname: rabbit-2
    container_name: rabbit-2
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "15673:15672"
      - "5673:5672"

  postgres-1:
    image: postgres:13.3
    container_name: postgres-1
    restart: always
    environment:
      POSTGRES_DB: "postgres-1"
      POSTGRES_USER: "postgresuser-1"
      POSTGRES_PASSWORD: "postgresuser-1"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin



